version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/env_variables.sh
      timeout: 300
      runas: ec2-user
      env:
        variables:
          DBCredentialsSecret: "${DBCredentialsSecret}"
          Region: "${Region}"
          DBEndpoint: "${DBEndpoint}"
          DBName: "${DBName}"
          PORT: "${PORT}"
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
