version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo "=== Generating Prisma Client ==="
      - npx prisma generate
      - echo "=== Building TypeScript ==="
      - npm run build
      - mkdir -p deploy
      - cp -r package.json package-lock.json dist appspec.yml scripts prisma deploy/
  post_build:
    commands:
      - echo "=== Build complete ==="
      - echo "=== Debugging Env Vars ==="
      - echo "DBCredentialsSecret=$DBCredentialsSecret"
      - echo "Region=$Region"
      - echo "DBEndpoint=$DBEndpoint"
      - echo "DBName=$DBName"
      - echo "PORT=$PORT"
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id "$DBCredentialsSecret" \
            --query SecretString \
            --output text \
            --region "$Region")

        DB_USER=$(echo $SECRET_JSON | jq -r .username)
        DB_PASS=$(echo $SECRET_JSON | jq -r .password)

        # Create .env for DB testing
        cat > deploy/.env <<EOF
        NODE_ENV=development
        DATABASE_URL=mysql://$DB_USER:$DB_PASS@$DBEndpoint:3306/$DBName
        PORT=$PORT
        EOF

      - echo "=== Debugging Env Vars ==="
      - cat deploy/.env

artifacts:
  files:
    - deploy/**/*
