version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building...
      - npm run build
      - mkdir -p deploy
      - cp -r package.json node_modules dist deploy/
      # create appspec.yml for CodeDeploy
      - cat > deploy/appspec.yml << 'EOF'
        version: 0.0
        os: linux
        files:
          - source: /
            destination: /var/www/todo
        hooks:
          AfterInstall:
            - location: scripts/install_dependencies.sh
              timeout: 300
              runas: ec2-user
          ApplicationStart:
            - location: scripts/start_server.sh
              timeout: 300
              runas: ec2-user
          ValidateService:
            - location: scripts/validate.sh
              timeout: 60
              runas: ec2-user
        EOF
      - mkdir -p deploy/scripts
      - cat > deploy/scripts/install_dependencies.sh << 'EOF'
        #!/bin/bash
        cd /var/www/todo
        npm ci --production || true
        EOF
      - cat > deploy/scripts/start_server.sh << 'EOF'
        #!/bin/bash
        cd /var/www/todo
        # stop existing pm2 app if any, then start
        pm2 delete todo || true
        pm2 start npm --name todo -- start
        EOF
      - cat > deploy/scripts/validate.sh << 'EOF'
        #!/bin/bash
        curl -f http://localhost:8080/health || exit 1
        EOF
artifacts:
  files:
    - deploy/**/*
  discard-paths: yes
