version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo "=== Generating Prisma Client ==="
      - npx prisma generate
      - echo "=== Building TypeScript ==="
      - npm run build
      - mkdir -p deploy
      - cp -r package.json package-lock.json dist scripts prisma deploy/
  post_build:
    commands:
      - echo "=== Build complete ==="
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id "$DBCredentialsSecret" \
            --query SecretString \
            --output text \
            --region "$Region")

        DB_USER=$(echo $SECRET_JSON | jq -r .username)
        DB_PASS=$(echo $SECRET_JSON | jq -r .password)

        # Create .env for DB testing
        cat <<EOF > deploy/.env
            NODE_ENV=development
            DATABASE_URL=mysql://$DB_USER:$DB_PASS@$DBEndpoint:3306/$DBName
            PORT=$PORT
        EOF

artifacts:
  files:
    - deploy/**/*
