version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo "=== Generating Prisma Client ==="
      - npx prisma generate
      - echo "=== Building TypeScript ==="
      - npm run build
      - mkdir -p deploy
      - cp -r package.json package-lock.json dist scripts prisma deploy/
  post_build:
    commands:
      - echo "=== Build complete ==="
      - |
        cat > deploy/appspec.yml <<EOF
            version: 0.0
            os: linux
            files:
              - source: /
                destination: /home/ec2-user/app
            permissions:
              - object: /home/ec2-user/app
                owner: ec2-user
                group: ec2-user
                mode: 755
            hooks:
              AfterInstall:
                - location: scripts/install_dependencies.sh
                  timeout: 300
                  runas: ec2-user
              ApplicationStart:
                - location: scripts/env_variables.sh
                  timeout: 300
                  runas: ec2-user
                  env:
                    variables:
                      DBCredentialsSecret: "${DBCredentialsSecret}"
                      Region: "${Region}"
                      DBEndpoint: "${DBEndpoint}"
                      DBName: "${DBName}"
                      PORT: "${PORT}"
                - location: scripts/start_server.sh
                  timeout: 300
                  runas: ec2-user
        EOF

artifacts:
  files:
    - deploy/**/*
