version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building...
      - npm run build
      - mkdir -p deploy
      - cp -r package.json node_modules dist appspec.yml scripts deploy/
artifacts:
  files:
    - deploy/**/*
  discard-paths: yes
